sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockeur_react -f dev.Dockerfile .

script:
  - docker run -e CI=true dockeur_react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'dockeur_react'
  env: 'Dockeurreact-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-276878536813'
  bucket_path: '"dockeur_react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
