version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - C:\Users\barto\OneDrive\Pulpit\dockerprojects\react\frontend:/app

  tests:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - C:\Users\barto\OneDrive\Pulpit\dockerprojects\react\frontend:/app
    command: ["npm", "run", "test"]